---
- name: "Deploy helloapp"
  hosts: localhost
  connection: local
  tasks:
    - name: "Add image to minikube"
      ansible.builtin.command:
        cmd: "minikube image build -t {{ image_name }} -f Containerfile ."
    - name: "Create Deployment for helloapp"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: helloapp-deployment
            namespace: default
            labels:
              app: helloapp
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: helloapp
            template:
              metadata:
                labels:
                  app: helloapp
              spec:
                containers:
                  - name: helloapp
                    image: "{{ image_name }}"
                    ports:
                      - containerPort: 8080
                        name: gunicorn
    - name: "Create Service for helloapp"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: helloapp-service
            namespace: default
          spec:
            type: NodePort
            selector:
              app: helloapp
            ports:
              - protocol: "TCP"
                port: 80
                targetPort: gunicorn
